module.exports = {
  ADD_SUCCESS: "ADD_SUCCESS",
  ADD_REQUEST: "ADD_REQUEST",
  ADD_FAILURE: "ADD_FAILURE",

  LIST_SUCCESS: "LIST_SUCCESS",
  LIST_REQUEST: "LIST_REQUEST",
  LIST_FAILURE: "LIST_FAILURE",

  SELECT_DISH_DETAILS: "SELECT_DISH_DETAILS",
  REMOVE_DISH_DETAILS: "REMOVE_DISH_DETAILS",

  ERROR: "ERROR",
};
